ssc install project
ssc install ranktest
ssc install eventstudy2
ssc install estout
ssc install mat2txt
ssc install ivreg2
ssc install coefplot
ssc install moreobs
ssc install mdesc
ssc install sutex
