ssc install cdfplot
ssc install carryforward
ssc install coefplot
ssc install estout
ssc install eventstudy2
ssc install fastreshape
ssc install latab
ssc install mat2txt
ssc install mdesc
ssc install mmerge
ssc install moreobs
ssc install ivreg2
ssc install palettes
ssc install project
ssc install grqreg
ssc install ranktest
ssc install reghdfe
ssc install sutex
