program usstates , rclass
syntax varlist(min=1 max=1) , newvar(string) type(string) 
	
	if "`type'" != "full" & "`type'" != "abbv"{
		di "Please provide a valid option for type (full or abbv)"
		exit
	}
	
	token `varlist'
	local var `1'
	
	qui gen `newvar' = ""

	if "`type'" == "full" {
		qui replace `newvar' = "AK" if `var' == "Alaska"
		qui replace `newvar' = "AL" if `var' == "Alabama"
		qui replace `newvar' = "AR" if `var' == "Arkansas"
		qui replace `newvar' = "AZ" if `var' == "Arizona"
		qui replace `newvar' = "CA" if `var' == "California"
		qui replace `newvar' = "CO" if `var' == "Colorado"
		qui replace `newvar' = "CT" if `var' == "Connecticut"
		qui replace `newvar' = "DC" if `var' == "DC"
		qui replace `newvar' = "DE" if `var' == "Delaware"
		qui replace `newvar' = "FL" if `var' == "Florida"
		qui replace `newvar' = "GA" if `var' == "Georgia"
		qui replace `newvar' = "HI" if `var' == "Hawaii"
		qui replace `newvar' = "IA" if `var' == "Iowa"
		qui replace `newvar' = "ID" if `var' == "Idaho"
		qui replace `newvar' = "IL" if `var' == "Illinois"
		qui replace `newvar' = "IN" if `var' == "Indiana"
		qui replace `newvar' = "KS" if `var' == "Kansas"
		qui replace `newvar' = "KY" if `var' == "Kentucky"
		qui replace `newvar' = "LA" if `var' == "Louisiana"
		qui replace `newvar' = "MA" if `var' == "Massachusetts"
		qui replace `newvar' = "MD" if `var' == "Maryland"
		qui replace `newvar' = "ME" if `var' == "Maine"
		qui replace `newvar' = "MI" if `var' == "Michigan"
		qui replace `newvar' = "MN" if `var' == "Minnesota"
		qui replace `newvar' = "MO" if `var' == "Missouri"
		qui replace `newvar' = "MS" if `var' == "Mississippi"
		qui replace `newvar' = "MT" if `var' == "Montana"
		qui replace `newvar' = "NC" if `var' == "North Carolina"
		qui replace `newvar' = "ND" if `var' == "North Dakota"
		qui replace `newvar' = "NE" if `var' == "Nebraska"
		qui replace `newvar' = "NH" if `var' == "New Hampshire"
		qui replace `newvar' = "NJ" if `var' == "New Jersey"
		qui replace `newvar' = "NM" if `var' == "New Mexico"
		qui replace `newvar' = "NV" if `var' == "Nevada"
		qui replace `newvar' = "NY" if `var' == "New York"
		qui replace `newvar' = "OH" if `var' == "Ohio"
		qui replace `newvar' = "OK" if `var' == "Oklahoma"
		qui replace `newvar' = "OR" if `var' == "Oregon"
		qui replace `newvar' = "PA" if `var' == "Pennsylvania"
		qui replace `newvar' = "RI" if `var' == "Rhode Island"
		qui replace `newvar' = "SC" if `var' == "South Carolina"
		qui replace `newvar' = "SD" if `var' == "South Dakota"
		qui replace `newvar' = "TN" if `var' == "Tennessee"
		qui replace `newvar' = "TX" if `var' == "Texas"
		qui replace `newvar' = "UT" if `var' == "Utah"
		qui replace `newvar' = "VA" if `var' == "Virginia"
		qui replace `newvar' = "VT" if `var' == "Vermont"
		qui replace `newvar' = "WA" if `var' == "Washington"
		qui replace `newvar' = "WI" if `var' == "Wisconsin"
		qui replace `newvar' = "WV" if `var' == "West Virginia"
		qui replace `newvar' = "WY" if `var' == "Wyoming"
	}

	if "`type'" == "abbv"{
		qui replace `newvar' = "Alaska" if `var' == "AK"
		qui replace `newvar' = "Alabama" if `var' == "AL"
		qui replace `newvar' = "Arkansas" if `var' == "AR"
		qui replace `newvar' = "Arizona" if `var' == "AZ"
		qui replace `newvar' = "California" if `var' == "CA"
		qui replace `newvar' = "Colorado" if `var' == "CO"
		qui replace `newvar' = "Connecticut" if `var' == "CT"
		qui replace `newvar' = "DC" if `var' == "DC"
		qui replace `newvar' = "Delaware" if `var' == "DE"
		qui replace `newvar' = "Florida" if `var' == "FL"
		qui replace `newvar' = "Georgia" if `var' == "GA"
		qui replace `newvar' = "Hawaii" if `var' == "HI"
		qui replace `newvar' = "Iowa" if `var' == "IA"
		qui replace `newvar' = "Idaho" if `var' == "ID"
		qui replace `newvar' = "Illinois" if `var' == "IL"
		qui replace `newvar' = "Indiana" if `var' == "IN"
		qui replace `newvar' = "Kansas" if `var' == "KS"
		qui replace `newvar' = "Kentucky" if `var' == "KY"
		qui replace `newvar' = "Louisiana" if `var' == "LA"
		qui replace `newvar' = "Massachusetts" if `var' == "MA"
		qui replace `newvar' = "Maryland" if `var' == "MD"
		qui replace `newvar' = "Maine" if `var' == "ME"
		qui replace `newvar' = "Michigan" if `var' == "MI"
		qui replace `newvar' = "Minnesota" if `var' == "MN"
		qui replace `newvar' = "Missouri" if `var' == "MO"
		qui replace `newvar' = "Mississippi" if `var' == "MS"
		qui replace `newvar' = "Montana" if `var' == "MT"
		qui replace `newvar' = "North Carolina" if `var' == "NC"
		qui replace `newvar' = "North Dakota" if `var' == "ND"
		qui replace `newvar' = "Nebraska" if `var' == "NE"
		qui replace `newvar' = "New Hampshire" if `var' == "NH"
		qui replace `newvar' = "New Jersey" if `var' == "NJ"
		qui replace `newvar' = "New Mexico" if `var' == "NM"
		qui replace `newvar' = "Nevada" if `var' == "NV"
		qui replace `newvar' = "New York" if `var' == "NY"
		qui replace `newvar' = "Ohio" if `var' == "OH"
		qui replace `newvar' = "Oklahoma" if `var' == "OK"
		qui replace `newvar' = "Oregon" if `var' == "OR"
		qui replace `newvar' = "Pennsylvania" if `var' == "PA"
		qui replace `newvar' = "Rhode Island" if `var' == "RI"
		qui replace `newvar' = "South Carolina" if `var' == "SC"
		qui replace `newvar' = "South Dakota" if `var' == "SD"
		qui replace `newvar' = "Tennessee" if `var' == "TN"
		qui replace `newvar' = "Texas" if `var' == "TX"
		qui replace `newvar' = "Utah" if `var' == "UT"
		qui replace `newvar' = "Virginia" if `var' == "VA"
		qui replace `newvar' = "Vermont" if `var' == "VT"
		qui replace `newvar' = "Washington" if `var' == "WA"
		qui replace `newvar' = "Wisconsin" if `var' == "WI"
		qui replace `newvar' = "West Virginia" if `var' == "WV"
		qui replace `newvar' = "Wyoming" if `var' == "WY"
	}


	if "`type'" == "full"{
		local var `newvar'
	}

	qui gen `newvar'_num = .

	qui replace `newvar'_num = 1 if `var' == "AK"
	qui replace `newvar'_num = 2 if `var' == "AL"
	qui replace `newvar'_num = 3 if `var' == "AR"
	qui replace `newvar'_num = 4 if `var' == "AZ"
	qui replace `newvar'_num = 5 if `var' == "CA"
	qui replace `newvar'_num = 6 if `var' == "CO"
	qui replace `newvar'_num = 7 if `var' == "CT"
	qui replace `newvar'_num = 8 if `var' == "DC"
	qui replace `newvar'_num = 9 if `var' == "DE"
	qui replace `newvar'_num = 10 if `var' == "FL"
	qui replace `newvar'_num = 11 if `var' == "GA"
	qui replace `newvar'_num = 12 if `var' == "HI"
	qui replace `newvar'_num = 13 if `var' == "IA"
	qui replace `newvar'_num = 14 if `var' == "ID"
	qui replace `newvar'_num = 15 if `var' == "IL"
	qui replace `newvar'_num = 16 if `var' == "IN"
	qui replace `newvar'_num = 17 if `var' == "KS"
	qui replace `newvar'_num = 18 if `var' == "KY"
	qui replace `newvar'_num = 19 if `var' == "LA"
	qui replace `newvar'_num = 20 if `var' == "MA"
	qui replace `newvar'_num = 21 if `var' == "MD"
	qui replace `newvar'_num = 22 if `var' == "ME"
	qui replace `newvar'_num = 23 if `var' == "MI"
	qui replace `newvar'_num = 24 if `var' == "MN"
	qui replace `newvar'_num = 25 if `var' == "MO"
	qui replace `newvar'_num = 26 if `var' == "MS"
	qui replace `newvar'_num = 27 if `var' == "MT"
	qui replace `newvar'_num = 28 if `var' == "NC"
	qui replace `newvar'_num = 29 if `var' == "ND"
	qui replace `newvar'_num = 30 if `var' == "NE"
	qui replace `newvar'_num = 31 if `var' == "NH"
	qui replace `newvar'_num = 32 if `var' == "NJ"
	qui replace `newvar'_num = 33 if `var' == "NM"
	qui replace `newvar'_num = 34 if `var' == "NV"
	qui replace `newvar'_num = 35 if `var' == "NY"
	qui replace `newvar'_num = 36 if `var' == "OH"
	qui replace `newvar'_num = 37 if `var' == "OK"
	qui replace `newvar'_num = 38 if `var' == "OR"
	qui replace `newvar'_num = 39 if `var' == "PA"
	qui replace `newvar'_num = 40 if `var' == "RI"
	qui replace `newvar'_num = 41 if `var' == "SC"
	qui replace `newvar'_num = 42 if `var' == "SD"
	qui replace `newvar'_num = 43 if `var' == "TN"
	qui replace `newvar'_num = 44 if `var' == "TX"
	qui replace `newvar'_num = 45 if `var' == "UT"
	qui replace `newvar'_num = 46 if `var' == "VA"
	qui replace `newvar'_num = 47 if `var' == "VT"
	qui replace `newvar'_num = 48 if `var' == "WA"
	qui replace `newvar'_num = 49 if `var' == "WI"
	qui replace `newvar'_num = 50 if `var' == "WV"
	qui replace `newvar'_num = 51 if `var' == "WY"

end
